[project]
name = "monorepo"
version = "0.1.0"
description = "More a shared repo than a monorepo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["bar", "foo"]